### ISSUE TITLE
ts-no-use-before-define: false positive when a stored function is only extracted, never invoked

### ISSUE THREAD

**Issue by rbaumier** [rbaumier/comply#8177]
> **Related to #6824** — that issue made a function stored in an object/array literal deferrable; this one is about the trigger test that decides when the stored function counts as reached.

## Context

`ts-no-use-before-define` treats a function stored in an object/array literal as deferred unless the owning variable is *reached* before the referenced declaration. The reach test is `binding_read_before` in `src/rules/ts_no_use_before_define/oxc_typescript.rs:675`: it counts **any** eager read of the variable.

Counting every read is the cheap sound rule — a call (`h.run()`), a getter read (`h.value`) and a setter write (`h.value = 1`) all go through a read. But it also counts a member read that only *extracts* the stored function and hands it to somebody else, which cannot run it. That is the ordinary event-handler registration shape.

## Repro

`repro/a.ts`:

```ts
declare const bus: { on(name: string, fn: () => number): void }

const reg = { onSave: () => store.value }
bus.on('save', reg.onSave)
const store = { value: 1 }
```

```
$ comply rules ts-no-use-before-define repro
repro/a.ts:3:29: error [ts-no-use-before-define] `store` is used before its definition.
```

1. `bus.on('save', reg.onSave)` reads `reg.onSave` to hand the arrow to a listener table; nothing invokes it during module evaluation → expected: silent / observed: `store` flagged.

Not a regression: the shape is flagged identically before and after #6824 (checked on both builds). Before that change the arrow was never deferred at all; now it is deferred, and `binding_read_before` re-flags it.

## Expected behavior

A read of the container variable counts as a trigger only when it can run something the literal stores. A member access that merely extracts a stored function, on a container that declares no accessor, does not.

## Root cause

`src/rules/ts_no_use_before_define/oxc_typescript.rs:681-685` (in `binding_read_before`) — the predicate is `reference.is_read() && span.start < decl_start && is_eagerly_reachable(..)`. It never looks at what the reference's parent does with the value, so extracting a property and invoking one are indistinguishable.

## Implementation details

- Files to modify (exact paths), all in `src/rules/ts_no_use_before_define/oxc_typescript.rs`:
  - `binding_read_before` (line 675) — the predicate.
  - Its docblock (line 667-674) — must state the three trigger shapes: an invoking member access, any member access on a container that declares an accessor, and a non-member read.
  - The module docblock, lines 85-89 — currently *"any eager read of the variable … keeps the reference flagged, because a call, a getter read and a setter write all go through such a read"*. Must state the narrowed trigger and the tolerated false negative below.
  - The `BindingReach::StoredInValue` variant doc, lines 577-580 — currently *"any read of the variable may run it"*. Same correction.
  - The *containers* bullet of `function_expression_binding`'s docblock (line 596-600) and the matching bullet of `is_deferred_function_expression`'s docblock (line 540-543) — both repeat the any-read rule.
- Pattern to follow: the callee-identity test in `binding_called_before` (same file, line 660-663) — it takes the reference's parent, matches `AstKind::CallExpression`, and compares `call.callee.span()` with the reference span. The new test asks the same question one or more member-access levels higher.
- Ordered steps:
  1. Classify each eager read by walking outward from the reference through member-access parents — `AstKind::StaticMemberExpression` and `AstKind::ComputedMemberExpression` (the repo idiom, see `src/oxc_helpers.rs:2083-2085`), transparently crossing `ParenthesizedExpression` and `TSNonNullExpression`. If one of them is the callee of a `CallExpression`, the read invokes — keep it a trigger. This covers `h.run()`, `h[key]()`, `h.run?.()`, `h!.run()` and `h.run.call(null)`.
  2. Any other member access — a plain read (`reg.onSave`) or an assignment target (`h.value = 1`) — is a trigger only when the container literal declares an accessor property (`PropertyKind::Get` / `PropertyKind::Set`); a data-only literal runs nothing on either. The gate is per container, not per property: an accessor anywhere in the literal keeps every member access a trigger, which keeps the test independent of key spelling. `function_expression_binding` already walks through that literal on its way to the declarator, so the answer can be carried out of that walk rather than recomputed from the symbol.
  3. Leave a **non-member** read alone — it stays a trigger. `register(h)`, `export default h` and `{ ...h }` hand the whole container away, and the rule already treats a function passed straight to a call as possibly invoked eagerly (`is_deferred_function_expression` docblock, line 536-537). Destructuring (`const { run } = h`) is a non-member read and also runs getters, so it stays a trigger for the same reason.
  4. Record the false negative step 2 introduces: extract-then-call through an intermediate binding (`const g = h.run; g(); const later = 1`) throws at runtime but becomes silent, because `h.run` is a non-invoking member access. Following the extracted value needs alias tracking, which is out of scope here; the file already has the convention of naming a tolerated false negative in the docblock (lines 549-551, 701-703). Name this one there and pin it with a test, so it is a decision rather than an accident.
  5. Update the five doc sites listed above; the repo convention is that a docblock describes current behaviour only.
- Edge cases:
  - Computed member access — `combinators[op]()` must stay a trigger whatever the key resolves to, so key spelling must not enter the test (step 1).
  - Accessor in the container — `const h = { get v() { return later } }; use(h.v); const later = 1` must stay flagged (step 2).
  - Mixed container — an accessor next to a data property makes *every* member access a trigger, including the extraction of the data property. Deliberate coarseness of step 2's per-container gate.
  - Setter write — `h.value = 1` on a literal declaring a setter must stay flagged (step 2).
  - The read must still pass `is_eagerly_reachable`; this issue only narrows *which* reads are candidates, not where they run.

## Tests

All in the `#[cfg(test)] mod tests` block of `src/rules/ts_no_use_before_define/oxc_typescript.rs`, matching the file's `no_fp_*` / `still_flags_*` naming.

- [ ] `no_fp_stored_arrow_only_registered_as_a_listener` — the repro above; asserts no diagnostic. Fails before the fix.
- [ ] `still_flags_stored_arrow_invoked_through_a_computed_member_call` — `h[key]()`; asserts one diagnostic (step 1, computed key).
- [ ] `still_flags_stored_arrow_invoked_through_a_chained_member_call` — `h.run.call(null)`; asserts one diagnostic (step 1, chained member).
- [ ] `still_flags_extraction_on_a_container_declaring_an_accessor` — `const h = { get v() { return later }, onSave: () => later }; bus.on('x', h.onSave); const later = 1`; asserts a diagnostic. Pins step 2's per-container gate as deliberate.
- [ ] `no_fp_stored_arrow_extracted_into_a_variable_then_called` — `const g = h.run; g(); const later = 1`; asserts no diagnostic, with a comment naming it as the tolerated false negative of step 4.
- [ ] `still_flags_container_handed_to_a_callee` — `register(h); const later = 1`; asserts one diagnostic, pinning step 3 as deliberate.
- [ ] Existing tests that must keep passing unchanged: `still_flags_arrow_stored_in_object_literal_read_eagerly_issue_6824` (line 2112, member call) and `still_flags_object_literal_accessor_triggered_eagerly_issue_6824` (line 2129, which already loops over the getter read and the setter write).
- [ ] Corpus check, recorded in the PR rather than as a unit test: `comply rules ts-no-use-before-define` on a large real TS project before/after. Every disappeared diagnostic must be read and confirmed to be an extraction shape.

## Out of scope

- `binding_called_before` (the directly-bound path) — its callee-identity test already excludes extraction.
- Alias tracking for the extracted-then-called shape of step 4.
- Deciding whether the callee of `register(h)` actually invokes what it received — that needs interprocedural analysis, and step 3 keeps the rule's existing conservative stance.
- The `BindingReach` container model itself, and the other deferral paths in the file (React hooks, Vue reactivity primitives, test-runner callbacks, TanStack Router factories, decorator thunks).
- Call-graph reachability of the read *site* — a separate issue, which depends on this one.
